name: Build and Deploy Next.js App

on:
  push:
    branches:
      - main # or 'master' or any deploy branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or your preferred version

      - name: 📥 Install dependencies
        run: npm install

      - name: 🛠️ Build Next.js app
        run: npm run build

      - name: ✅ Run tests
        run: npm test || echo "No tests"

      - name: 📤 Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next/
